<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Ramsey\Uuid\Uuid;

class InternalCodesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('internal_codes')->insert([
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'OPERATOR_STATUS', 'key' => '0', 'value' => '新規登録' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'OPERATOR_STATUS', 'key' => '1', 'value' => '作成中' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'OPERATOR_STATUS', 'key' => '2', 'value' => '編集完了' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'OPERATOR_STATUS', 'key' => '3', 'value' => '審査中' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'OPERATOR_STATUS', 'key' => '4', 'value' => '修正依頼' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'OPERATOR_STATUS', 'key' => '5', 'value' => '承認済' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'OPERATOR_STATUS', 'key' => '6', 'value' => '登録却下' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'OPERATOR_CATEGORY', 'key' => '1', 'value' => '法人' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'OPERATOR_CATEGORY', 'key' => '2', 'value' => '個人事業主' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '1', 'value' => '国土交通大臣' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '01', 'value' => '北海道知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '02', 'value' => '青森県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '03', 'value' => '岩手県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '04', 'value' => '宮城県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '05', 'value' => '秋田県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '06', 'value' => '山形県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '07', 'value' => '福島県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '08', 'value' => '茨城県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '09', 'value' => '栃木県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '10', 'value' => '群馬県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '11', 'value' => '埼玉県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '12', 'value' => '千葉県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '13', 'value' => '東京都知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '14', 'value' => '神奈川県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '15', 'value' => '新潟県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '16', 'value' => '富山県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '17', 'value' => '石川県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '18', 'value' => '福井県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '19', 'value' => '山梨県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '20', 'value' => '長野県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '21', 'value' => '岐阜県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '22', 'value' => '静岡県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '23', 'value' => '愛知県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '24', 'value' => '三重県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '25', 'value' => '滋賀県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '26', 'value' => '京都府知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '27', 'value' => '大阪府知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '28', 'value' => '兵庫県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '29', 'value' => '奈良県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '30', 'value' => '和歌山県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '31', 'value' => '鳥取県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '32', 'value' => '島根県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '33', 'value' => '岡山県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '34', 'value' => '広島県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '35', 'value' => '山口県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '36', 'value' => '徳島県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '37', 'value' => '香川県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '38', 'value' => '愛媛県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '39', 'value' => '高知県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '40', 'value' => '福岡県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '41', 'value' => '佐賀県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '42', 'value' => '長崎県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '43', 'value' => '熊本県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '44', 'value' => '大分県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '45', 'value' => '宮崎県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '46', 'value' => '鹿児島県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'CONSTRUCTION_CATEGORY', 'key' => '47', 'value' => '沖縄県知事' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '00', 'value' => '国土交通大臣' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '01', 'value' => '北海道' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '02', 'value' => '青森' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '03', 'value' => '岩手' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '04', 'value' => '宮城' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '05', 'value' => '秋田' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '06', 'value' => '山形' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '07', 'value' => '福島' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '08', 'value' => '茨城' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '09', 'value' => '栃木' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '10', 'value' => '群馬' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '11', 'value' => '埼玉' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '12', 'value' => '千葉' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '13', 'value' => '東京' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '14', 'value' => '神奈川' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '15', 'value' => '新潟' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '16', 'value' => '富山' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '17', 'value' => '石川' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '18', 'value' => '福井' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '19', 'value' => '山梨' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '20', 'value' => '長野' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '21', 'value' => '岐阜' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '22', 'value' => '静岡' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '23', 'value' => '愛知' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '24', 'value' => '三重' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '25', 'value' => '滋賀' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '26', 'value' => '京都' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '27', 'value' => '大阪' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '28', 'value' => '兵庫' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '29', 'value' => '奈良' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '30', 'value' => '和歌山' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '31', 'value' => '鳥取' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '32', 'value' => '島根' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '33', 'value' => '岡山' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '34', 'value' => '広島' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '35', 'value' => '山口' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '36', 'value' => '徳島' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '37', 'value' => '香川' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '38', 'value' => '愛媛' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '39', 'value' => '高知' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '40', 'value' => '福岡' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '41', 'value' => '佐賀' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '42', 'value' => '長崎' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '43', 'value' => '熊本' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '44', 'value' => '大分' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '45', 'value' => '宮崎' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '46', 'value' => '鹿児島' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '47', 'value' => '沖縄' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '50', 'value' => '北海道（石狩）' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '51', 'value' => '北海道（渡島）' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '52', 'value' => '北海道（檜山）' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '53', 'value' => '北海道（後志）' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '54', 'value' => '北海道（空知）' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '55', 'value' => '北海道（上川）' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '56', 'value' => '北海道（留萌）' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '57', 'value' => '北海道（宗谷）' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '58', 'value' => '北海道（オホ）' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '59', 'value' => '北海道（胆振）' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '60', 'value' => '北海道（日高）' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '61', 'value' => '北海道（十勝）' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '62', 'value' => '北海道（釧路）' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REAL_ESTATE_CATEGORY', 'key' => '63', 'value' => '北海道（根室）' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REFORM_ASSOCIATION', 'key' => '01', 'value' => '一般社団法人日本住宅リフォーム産業協会' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REFORM_ASSOCIATION', 'key' => '02', 'value' => '日本木造住宅耐震補強事業者協同組合' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REFORM_ASSOCIATION', 'key' => '03', 'value' => '一般社団法人リノベーション協議会' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REFORM_ASSOCIATION', 'key' => '04', 'value' => '一般社団法人ベターライフリフォーム協会' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REFORM_ASSOCIATION', 'key' => '05', 'value' => '一般社団法人日本塗装工業会' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REFORM_ASSOCIATION', 'key' => '06', 'value' => '一般社団法人リフォームパートナー協議会' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REFORM_ASSOCIATION', 'key' => '07', 'value' => '一般社団法人全建総連リフォーム協会' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REFORM_ASSOCIATION', 'key' => '08', 'value' => '一般社団法人住生活リフォーム推進協会' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REFORM_ASSOCIATION', 'key' => '09', 'value' => '一般社団法人JBN・全国工務店協会' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REFORM_ASSOCIATION', 'key' => '10', 'value' => '一般社団法人住宅リフォーム推進サポート協議会' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REFORM_ASSOCIATION', 'key' => '11', 'value' => '一般社団法人住活協リフォーム' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REFORM_ASSOCIATION', 'key' => '12', 'value' => '一般社団法人全国古民家再生協会' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REFORM_ASSOCIATION', 'key' => '13', 'value' => '一般社団法人木造住宅塗装リフォーム協会' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REFORM_ASSOCIATION', 'key' => '14', 'value' => '一般社団法人ステキ信頼リフォーム推進協会' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REFORM_ASSOCIATION', 'key' => '15', 'value' => '一般社団法人日装連リフォーム推進協議会' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'REFORM_ASSOCIATION', 'key' => '16', 'value' => '一般社団法人マンション計画修繕施工協会' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'KINYU_KIKAN_YOKIN_KUBUN', 'key' => '1', 'value' => '普通' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'KINYU_KIKAN_YOKIN_KUBUN', 'key' => '2', 'value' => '当座' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'KINYU_KIKAN_YOKIN_KUBUN', 'key' => '4', 'value' => '貯蓄' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'KINYU_KIKAN_YOKIN_KUBUN', 'key' => '9', 'value' => 'その他' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'FILE_TYPE', 'key' => '1', 'value' => '1_住宅省エネ2023キャンペーン・住宅省エネ支援事業者登録申請書（添付する印鑑証明書の登録印を押してください）' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'FILE_TYPE', 'key' => '2', 'value' => '2_商業法人登記の写し' ],
            [ 'id' => Uuid::uuid4()->toString(), 'identification_name' => 'FILE_TYPE', 'key' => '3', 'value' => '3_印鑑証明書（法人は法人、個人事業主は個人のもの）' ],
        ]);
    }
}
